@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;