@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.math;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;