@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.spawner;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;