@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.world;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;