@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.tileentity;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;