@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.concurrent;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;