@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.main;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;