@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.loot.functions;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;