@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.status;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;