@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.datasync;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;