@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command.arguments;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;