@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.scoreboard;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;