@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command.arguments.serializers;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;