@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.particles;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;