@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.util;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;