@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.network.status;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;