@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command.impl;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;