@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.text.filter;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;