@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.state.properties;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;