@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.settings;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;