@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.inventory.container;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;