@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.lighting;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;