@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.text;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;