@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;