@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.renderer.model.multipart;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;