@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.pathfinding;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;