@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.biome;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;