@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.registry;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;