@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.status.server;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;