@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.server.integrated;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;