@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.dispenser;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;