@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.border;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;