@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.profiler;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;