@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.block.material;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;