@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.block.pattern;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;