@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;