@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.palette;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;