@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.enchantment;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;