@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.multiplayer;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;