@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.resources;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;