@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.util.math.shapes;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;