@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.tutorial;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;