@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.shader;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;