@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.item.crafting;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;