@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.network.login.server;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;