@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.audio;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;